version: "3"
services:
  web:
    container_name: scrundar-www
    build: .
    working_dir: /code
    ports:
      - 8000:8000
      - 8080:8080
    volumes:
      - .:/code
    tty: true
    depends_on:
      - db
    # networks:
    #   - frontend
    #   - backend

  db:
    container_name: scrundar-db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: scrundar-db
      MYSQL_USER: frappuccino
      MYSQL_PASSWORD: aki08hiro22yuto
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql_data:/var/lib/mysql
      - ./db/mysql_confd:/etc/mysql/conf.d
      # - .db/mysql_init:/docker-entrypoint-initdb.d
    # networks:
    #   - backend

  front:
    container_name: scrundar-front
    image: node:14.15.4
    working_dir: /code
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - .:/code
    tty: true
    depends_on:
      - web
#     networks:
#       - frontend
# networks:
#   frontend:
#     driver: bridge
#   backend:
#     driver: bridge
