# Generated by Django 3.1.6 on 2021-03-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210209_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='application_status_to_team',
            field=models.CharField(choices=[('applying', '申請中'), ('unapplied', '未申請')], default='unapplied', max_length=9),
        ),
    ]
